apiVersion: apps/v1
kind: Deployment
metadata:
  name: aichat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aichat-ui
  template:
    metadata:
      labels:
        app: aichat-ui
    spec:
      containers:
      - name: aichat-ui
        image: samos123/aichat-ui
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: aichat-ui
spec:
  type: ClusterIP
  selector:
    app: aichat-ui
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
